spring.application.name=SpringView
spring.web.resources.static-locations=file:/C:/Users/lewis/stream/,classpath:/static/

stream.playlistDir=C:\\Users\\lewis\\stream
stream.audioDevice=CABLE Output (VB-Audio Virtual Cable)

soundVolumeView.audioDevice.old=Speakers
soundVolumeView.audioDevice.new=CABLE Input

server.port=1991
